sudo: required
services:
  - docker

before_install:
  - docker build -t nelobaba/docker-react -f Dockerfile.dev .
script:
  - docker run -e CI=true nelobaba/docker-react npm run test

deploy:
  provider: elasticbeanstalk
  region: "ca-central-1"
  app: "dockerize"
  env: "Dockerize-env"
  bucket_name: "elasticbeanstalk-ca-central-1-645095867705"
  bucket_path: "dockerize"
  on:
    branch: master
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key: $AWS_ACCESS_SECRET
